### ISSUE TITLE
Compound having expressions are broken

### ISSUE THREAD

**Issue by lloydtabb** [malloydata/malloy#1004]
```
source: airports is table('duckdb:airports.parquet') {
  measure: airport_count is count()
  measure: county_count is count(distinct county)

  query: by_state is {
    having: airport_count > 20 or county_count > 100
    group_by: state
    aggregate: airport_count
  }
}
```

**Comment by mtoy-googly-moogly** [comment]
Yeah the type checking engine inside the expression compiler is pretty sketchy. Almost certainly got broken by introducing window functions. Probably easy to fix.

I'd wait til @gmaden merges the re-org of lang/ though.

**Comment by christopherswenson** [comment]
Oh, well here's a fix for this... Can wait for the re-org... https://github.com/malloydata/malloy/pull/1006
