### ISSUE TITLE
"File not found" in SQL Turducken when querying from Source

### ISSUE THREAD

**Issue by carlineng** [malloydata/malloy#1008]
When querying from a Source inside of a Turducken, I'm getting a "No files found that match pattern" error. The same query compiles just fine when used outside of the Turducken.

In my example, the Turducken is a SQL query that has a Malloy query as the `from` clause. The inner Malloy query uses a named Source. For a simple example, see [this snippet from the Malloy samples repo](https://github.com/malloydata/malloy-samples/pull/13).

![image](https://user-images.githubusercontent.com/79773/216476144-a391aeea-a0cd-4c28-9ac9-ce9bf0168ea3.png)

**Comment by whscullin** [comment]
@carlineng I think I've fixed the initial bug, now I'm getting
```
Error(s) compiling model:
FILE: file:///Users/willscullin/src/malloydata/malloy-samples/duckdb/names/foo.malloy
line 12: Invalid SQL, Syntax error: Unexpected string literal "name" at [6:10]
  |   select: """
  |           ^
```
which is probably a separate issue with Turducken or possibly just with our error messages (I'm not seeing a way to get the actual problematic SQL.)

**Comment by carlineng** [comment]
@whscullin has the change made it a VSCode release yet? I'm trying it out on both the pre-releases (v0.3.1676662669) and the most recent stable release (v0.2.1676392777), and am still seeing the same error.

**Comment by whscullin** [comment]
It should be in the latest version, although I just fixed a similar bug that was affecting the browser based version.

**Comment by whscullin** [comment]
OK, I think I understand what's going on - the SQL generated by the inner Malloy is being sent to a "default" connection, not the connection associated with the `source`. In the case of DuckDB, there's a connection per folder, and the "default" is somehow referencing a different folder.

In my case, my default database connection was a BigQuery connection, and it was getting really confused because we still send it DuckDB syntax. That is why I get `Unexpected string literal "name"` instead of `No files found`

**Comment by whscullin** [comment]
It's using the connection of the sql block, which, if unspecified, would be the default connection. If I update your test case to be:
```malloy
sql: names_sql is {
  connection: "duckdb"
  select: """
    SELECT
    ROW_NUMBER() OVER (ORDER BY population) as row_number,
      *
    FROM (%{
      names -> {
        group_by: name
        aggregate: population
      }
    }%)
  """
}
```
then it works for me. What "connection" is might be configuration specific.

@mtoy-googly-moogly Might have some insight into whether this is the expected behavior.

**Comment by carlineng** [comment]
Oh interesting, thanks for tracking that down! I'll try adding the connection string, and see if that's a feasible workaround for the time being.

**Comment by mtoy-googly-moogly** [comment]
I think the SQL block should inherit the connection from the query, I'll see if i can make that happen.

**Comment by mtoy-googly-moogly** [comment]
This goes away with m4, as all sql code always has a connection.
