### ISSUE TITLE
Time literals with hour granularity

### ISSUE THREAD

**Issue by mtoy-googly-moogly** [malloydata/malloy#1049]
* `timeStamp ? @2001-01-02 04:05` true if timeStamp is in the minute specified
* `timeStamp ? @2001-01-02` true if time timeStamp is in the day specified
* `timeStamp ? @2001-01` true if timeStamp is in the month specified
* `timeStamp ? @2001` true if timeStamp is in the year specified

We should probably also support `YYYY-MM-DD HH` to make an hour granularity literal, it would take ten minutes to do, but I am filing this as an issue in case it is a bad idea for reasons I am not aware of. Assigning to lloyd just to get a thumb up or down.

**Comment by lloydtabb** [comment]
Yes please.

**Comment by mtoy-googly-moogly** [comment]
Done in #1048
