### ISSUE TITLE
schema caching and sql blocks somehow broken

### ISSUE THREAD

**Issue by mtoy-googly-moogly** [malloydata/malloy#1064]
From slack:

> "Let's say I have two Malloy sources and I use a sql: block to UNION them via Turducken. I then also have a Malloy source that uses from_sql() to create itself from the sql block. Then I have other Malloy sources and queries that build off of that from_sql() Malloy source. All of this works fine...until I rename one of the dimensions used in the original two Malloy sources UNION'd via Turducken. When a dimension is renamed in a source UNION'd by Turducken, all usage of the Malloy source built off of the sql: block throws syntax errors saying the newly named dimension doesn't exist. This can be fixed by simply force quitting VSCode and reloading it, so I'm guessing there's some sort of caching going on and there isn't logic to refresh it when Turducken is in use:"

Not 100% sure this is a extension issue, could be in the runtime.

**Comment by mtoy-googly-moogly** [comment]
I believe this was fixed in https://github.com/malloydata/malloy/pull/1062 however the user is still seeing problems, holding this open.

**Comment by whscullin** [comment]
We haven't pushed a release in over two weeks, I guess. Time flies. Doing that now.

**Comment by mtoy-googly-moogly** [comment]
This has had enough soak time, closing.
