### ISSUE TITLE
We need a way to cast to native types.

### ISSUE THREAD

**Issue by lloydtabb** [malloydata/malloy#1094]
I think there are always going to be times that we want to cast to a native type in a database.  It would be great if there were some syntax for that in Malloy.  Maybe..

We just hit this on slack (again).  @christopherswenson will make it occur less, but I still think we're going to want to be able to control the types of output tables....

```
group_by: foo_int64 is foo::"int64"
```

**Comment by mtoy-googly-moogly** [comment]
Yup .. `::QUOTED_THING` is one idea I've had too. We should talk about `CAST` and `SAFE_CAST` and wrap all three of these up in one "make casting more correct" language change. There's already an item on the roadmap for this.
