### ISSUE TITLE
Adding a filter to a constant should report a compiler error, seems to ignore.

### ISSUE THREAD

**Issue by lloydtabb** [malloydata/malloy#1100]
![image](https://user-images.githubusercontent.com/1093458/236684510-c56077a8-96cd-42e2-9749-e24a3ce48937.png)

**Comment by mtoy-googly-moogly** [comment]
This does raise the question about whether the priority of `{}` should be lower. Opinions @lloydtabb @christopherswenson ?

**Comment by mtoy-googly-moogly** [comment]
( AND we should generate an error )

**Comment by lloydtabb** [comment]
> This does raise the question about whether the priority of `{}` should be lower. Opinions @lloydtabb @christopherswenson ?

I don't think so.   `a{}/b{}` wouldn't work very well because it would evaluate to `(a{}/b){}` which would also fliter `a`.

**Comment by mtoy-googly-moogly** [comment]
Your example `expr1 { where: } / expr2 { where: }` is interesting. I agree that there `where:` should happen before the division, and if it has higher priority than division, it has higher priority than `>` obviously. I think I can make a good error message. On it.

**Comment by mtoy-googly-moogly** [comment]
Somewhat amusingly, there was code which detected this and then because it seemed like future somebodies problem, did nothing when it was detected.

**Comment by christopherswenson** [comment]
Agree with Lloyd, the precedence seems okay for now. Just another case for us to think about in the syntax overhaul.
