### ISSUE TITLE
.malloyqsql should wrap %{ in (

### ISSUE THREAD

**Issue by mtoy-googly-moogly** [malloydata/malloy#1104]
.. and for extra credit, don't wrap if the source is already wrapped

```
;;; sql 
CREATE TABLE AS %{ -> malloyQuery }%
;;; sql
CREATE TABLE AS (%{ -> malloyQuery }%)
```

both generate only one paren around the select statement

**Comment by bporterfield** [comment]
Parser identifies whether or not an embedded Malloy stmt was parenthized, which allows for deciding if wrapping resulting SQL in parens is necessary, [see here](https://github.com/malloydata/malloy/blob/main/packages/malloy-malloy-sql/src/malloySQLParser.ts#L197) via
