### ISSUE TITLE
Schema Cache in MalloySQL is a problem

### ISSUE THREAD

**Issue by lloydtabb** [malloydata/malloy#1134]
I'm playing with something like this.  I change the name of the output column 'a' and the  second time the query fails with 'column does not exist'.  Not sure how to solve

```
>>>sql connection:duckdb

copy (
	SELECT 1 as a
) to 'one.parquet' (FORMAT 'parquet', CODEC 'ZSTD')

>>>malloy

query: table('duckdb:one.parquet')-> {project: * }
```

**Comment by bporterfield** [comment]
After talking it over:

- Schema cache is an issue for malloySQL and malloy - today, any change to schema when running malloy will result in a schema cache issue. This is probably an issue you would encounter more often in malloySQL, but could definitely also affect malloy (esp when working with duckdb + parquet/csv etc).
- Schema cache is application-specific and should move to application layer (see #1183)
- VSCode extension should provide way to invalidate schema cache
