### ISSUE TITLE
_TABLE_SUFFIX filtering fails in certain cases 

### ISSUE THREAD

**Issue by amitaggarwal1** [malloydata/malloy#1147]
Question about using wild card tables and TABLE_SUFFIX. I am using a source with a * pattern. In a lot of cases, filtering by table suffix works fine. In some other cases, it fails (SQL gets generated but the SQL does not run). Typically this happens when the SQL has something of the form:
FROM (SELECT GENERATE_UUID() as __distinct_key, * FROM `{{projectId}}.events_*` as x) as events
Note that the FROM is using another SELECT which generates the UUID. Now using TABLE_SUFFIX on the events table which is dervied fails

**Comment by lloydtabb** [comment]
And a great solution.

`SELECT GENERATE_UUID() as __distinct_key, *, _TABLE_SUFFIX FROM `events_*` as x`

![image](https://github.com/malloydata/malloy/assets/1093458/8f4e5f60-26e1-4035-9637-9b10024ae4a0)

**Comment by lloydtabb** [comment]
This should be available in the VSCode plugin next time we update the Malloy module.
