### ISSUE TITLE
Implement new rules for query refinement

### ISSUE THREAD

**Issue by christopherswenson** [malloydata/malloy#1172]
* `aggregate:`, `group_by:`, and `calculate:` are not legal when refining a multi stage query
* `where:` refines the first stage of the query
* Everything else refines the last stage of the query (`limit:`, `having:`, `order_by:`)

**Comment by christopherswenson** [comment]
I assume `extend:` will only be legal in one-stage queries as well, though we haven't discussed this.

**Comment by mtoy-googly-moogly** [comment]
This is done in https://github.com/malloydata/malloy/pull/1241
