### ISSUE TITLE
Deprecate turtles without leading arrows

### ISSUE THREAD

**Issue by christopherswenson** [malloydata/malloy#1182]
Add a warning when defining turtles without a leading arrow.

Warning: `query: foo is { ... }`. No warning: `query: foo is -> { ... }`. 

Warning should be like "Query definitions inside a source should start with an arrow (e.g. `query_name is -> { ... }`) or another query name (e.g. `query_name is other_query -> { ... }`)".

## -> should be a warning in m4 and illegal in 4.0

* [ ] @lloydtabb 
* [ ] @christopherswenson 
* [ ] @carlineng 
* [x] @mtoy-googly-moogly

**Comment by christopherswenson** [comment]
I believe we discussed that this is actually not a warning to not have a leading arrow, it's just going to be straight up optional for the moment.

**Comment by mtoy-googly-moogly** [comment]
Leaving open because we need to decide if the arrow is required in m4 or now.

**Comment by lloydtabb** [comment]
Wait, I'm confused. Is this what we are voting for?

Correct syntax:
```
view: foo is { 
view: bar is x + {
```

Incorrect syntax is 

```
view: foo is -> { 
view: bar is -> x + {
```

**Comment by mtoy-googly-moogly** [comment]
We are voting if the "incorrect" syntax is accepted forever, or if it becomes illegal in 4.0

@christopherswenson said above " it's just going to be straight up optional for the moment."

I think it needs to be an m4 warning, thus the vote.

**Comment by carlineng** [comment]
I'm confused, as it seems like there is disagreement on what the "correct" vs "incorrect" syntax should be. It sounds like Lloyd is saying `query: foo is { ... }` should be the correct syntax, but if I interpret Chris's original comment correctly, he is saying `query: foo is -> { ... }` is the correct syntax?

**Comment by christopherswenson** [comment]
My comment was old, when we thought there should be an arrow

Poll to confirm that correct is `view: x is { ... }` and that `view: x is -> { ... }` is a warning.

- [ ] @carlineng 
- [ ] @lloydtabb 
- [ ] @mtoy-googly-moogly 
- [x] @christopherswenson

**Comment by carlineng** [comment]
Awesome, thanks for clarifying. 👍 from me.

**Comment by mtoy-googly-moogly** [comment]
cool .. i'll get a PR with the warning up
