### ISSUE TITLE
"Run" keyword doesn't work as expected with query refinements on top-level named queries

### ISSUE THREAD

**Issue by carlineng** [malloydata/malloy#1236]
If I have a named query, I cannot add a query refinement and execute the query with the `run:` keyword.

Example -- here's a named query:

```
query: by_dest is flights -> {
  group_by:
    destination

  aggregate:
    flight_count
}
```

This runs the query:
```
run: by_dest
```

But I cannot do this:

```
run: by_dest + {
   group_by: origin
}
```

I get an error saying: `no viable alternative at input '{group_by:'`

I created an example of the issue in a [branch of the malloy-samples repo](https://github.com/malloydata/malloy-samples/blob/ad42c41f7ec43bcb9284f8b0de1284622b96a8c0/duckdb/faa/query_refinement_bug.malloy#L27-L30)

![image](https://github.com/malloydata/malloy/assets/79773/8d11db7f-9647-4728-9a20-63907d43b0d9)

**Comment by carlineng** [comment]
Query refinements works fine if I execute a turtle --

```
run: flights -> top_destinations + {
  group_by: origin
}
```
works fine.

But if I attempt this on a named-query, it fails.

**Comment by mtoy-googly-moogly** [comment]
```
query: by_dest is duckdb.table('duckdb/data/flights.parquet') -> {
  group_by:
    destination

  aggregate:
    flight_count is count()
}

run: by_dest + { group_by: origin }
```

Works today. Can I close @carlineng ?

**Comment by carlineng** [comment]
Confirmed fixed. Thanks @mtoy-googly-moogly!
