### ISSUE TITLE
ltrim function thinks it returns a number

### ISSUE THREAD

**Issue by carlineng** [malloydata/malloy#1281]
### What happens?

I'm trying to write a query that does `substr(ltrim('   somvalue'), 1, 20)`, and the Malloy compiler is complaining that `substr` doesn't take `number, number, number`, which makes me think `ltrim` is trying to return a number.

![image](https://github.com/malloydata/malloy/assets/79773/cae32825-12b2-429c-97c6-4ed328b6fe38)

### To Reproduce

Try the following Malloy code:

```
source: test_src is duckdb.sql("select '    hello world' as col1")

run: test_src -> {
  project:
    col1
    substr_col1 is substr(col1, 1, 5)
    substr_trim_col1 is substr(ltrim(col1), 1, 5) -- this column creates a compiler error
}
```

### OS:

macOS

### Malloy Client:

VSCode

### Malloy Client Version:

v0.2.1691507880

### Database Connection:

DuckDB and BigQuery

**Comment by christopherswenson** [comment]
Yep, copy paste error on my part. 

Here's where it's defined: https://github.com/malloydata/malloy/blob/main/packages/malloy/src/dialect/functions/trim_functions.ts

The return overload should say `string` not `number`.

**Comment by carlineng** [comment]
Awesome, thanks for the quick fix @christopherswenson !
