### ISSUE TITLE
Incorrect results with `calculate` and `lag`

### ISSUE THREAD

**Issue by carlineng** [malloydata/malloy#1284]
### What happens?

See [this query](https://github.com/malloydata/malloy-samples/blob/37eae3873b8624fa16042b8264e0a916bd9c6739/duckdb/names/names.malloy#L192-L208) for an example:

```
run: names -> {
  group_by:
    year_born
  
  aggregate:
    f_count is count() { where: gender = 'F' }
    m_count is count() { where: gender = 'M' }

  calculate:
    f_count_change is f_count - lag(f_count)
    m_count_change is m_count - lag(m_count)

    diff_change_wrong is f_count_change - m_count_change
    diff_change_right is (f_count_change) - (m_count_change)

  order_by: year_born
}
```

`diff_change_wrong` and `diff_change_right` should produce the same results, but they produce different ones:

![image](https://github.com/malloydata/malloy/assets/79773/d5f85774-4aeb-4993-93b1-a4664ac26717)

### To Reproduce

Run the query on this branch: https://github.com/malloydata/malloy-samples/blob/37eae3873b8624fa16042b8264e0a916bd9c6739/duckdb/names/names.malloy#L192-L208

### OS:

macOS

### Malloy Client:

VSCode extension

### Malloy Client Version:

v0.3.1691686196

### Database Connection:

DuckDB and BQ

**Comment by christopherswenson** [comment]
Minimal example:

```malloy
run: aircraft -> {
  group_by:
    r is 1

  calculate:
    diff is 1 - rank()
    diff_bare  is 1 - diff
    diff_paren is 1 - (diff)
}
```

**Comment by christopherswenson** [comment]
This is a pretty silly error. What's happening is that the negation doesn't parenthesize the RHS in a `calculate` for some reason, when it does in a `group_by`. Looking into exactly why. Result is that `diff_bare = 1 - 1 - rank()` whereas `diff_paren = 1 - (1 - rank())`... Doh.
