### ISSUE TITLE
Language Proposal use the keyword `view:`  instead of `query:` in a `source:`

### ISSUE THREAD

**Issue by lloydtabb** [malloydata/malloy#1350]
```
source: airports is ... {
  query: by_state is ...
}
```
becomes 
```
source: airports is ... {
  view: by_state is ...
}
```

Please sign off when you are ready.

- [x] @mtoy-googly-moogly 
- [x] @lloydtabb 
- [x] @christopherswenson 
- [x] @carlineng

**Comment by mtoy-googly-moogly** [comment]
I understood lloyd was ready several days ago on this. I am waiting for more than once anecdote before I will sign off. I was promised 10, but really three would be plenty.

**Comment by lloydtabb** [comment]
I have exposed this to many people.  Everyone understood it.  Most did it without thinking.  @christopherswenson @mtoy-googly-moogly sign-off?  I'd like to land the samples changes...

**Comment by mtoy-googly-moogly** [comment]
OK, this passes. I will work through the ramifications.
