### ISSUE TITLE
Parse error on any string containing a tab character

### ISSUE THREAD

**Issue by carlineng** [malloydata/malloy#1402]
### What happens?

[From Slack](https://malloy-community.slack.com/archives/C025JAK8G0N/p1696960582481639):

Something about having a tab symbol within the concat() function breaks things. Previously, this would work fine:
`dimension: xyz is concat(abc, '  ')`, Where within the '' is a tab and not spaces. However, now it throws this syntax error:
`mismatched input ''' expecting ')'`

### To Reproduce

Create a dimension that uses the `concat` function, and contains a tab as an argument.

https://github.com/malloydata/malloy-samples/blob/6b5caa3081a05f1d809402916f31cfee8169d5d7/faa/airports.malloy#L6-L7

### OS:

All OSs

### Malloy Client:

All clients

### Malloy Client Version:

VSCode Extension v0.3.1696891939

### Database Connection:

BigQuery and DuckDB

**Comment by mtoy-googly-moogly** [comment]
```
run: duckdb.sql("select 1") -> { select: tabChar is '	 ' }
```

```
mismatched input ''' expecting {ALL, AVG, CAST, COUNT, DAY, EXCLUDE, FALSE, HOUR, MAX, MIN, MINUTE, MONTH, NOT, NOW, NULL, PICK, QUARTER, SECOND, SOURCE_KW, SUM, TRUE, WEEK, YEAR, HACKY_REGEX, SQ_STRING, DQ_STRING, BQ_STRING, '(', '-', LITERAL_TIMESTAMP, LITERAL_HOUR, LITERAL_DAY, LITERAL_QUARTER, LITERAL_MONTH, LITERAL_WEEK, LITERAL_YEAR, IDENTIFIER, NUMERIC_LITERAL, INTEGER_LITERAL, '"""'}
```

has nothing to do with concat, we just can't parse tabs for some reason.
