### ISSUE TITLE
join_many/with is never legal

### ISSUE THREAD

**Issue by lloydtabb** [malloydata/malloy#1436]
The statement below is never legal and should be caught by the parser.  Right now the error is generated by the code generator and is confusing.
```
 join_many: states_with_ballon_ports with state 
```

**Comment by mtoy-googly-moogly** [comment]
Weird there is a check for it ...

```
        } else if (join instanceof ast.KeyJoin) {
          join.log('Foreign key join not legal in join_many:');
        }
```

But i guess there is no test, because you are saying you don't see that error.  On it

**Comment by mtoy-googly-moogly** [comment]
Yeah the error was caught by the parser, but it was going into a wrong bucket.  Fix coming.
