### ISSUE TITLE
Vs Code Notebook Malloy runtime leaking postgres connections

### ISSUE THREAD

**Issue by kylenesbit** [malloydata/malloy#1439]
### What happens?

After executing my Malloy VS Code Notebook  several times, I get a "sorry, too many clients already" error from postgres.  It seems the Malloy runtime is creating & leaving open many connections to the database.  I have to restart the database server to reset the connection state in order to execute the notebook.

### To Reproduce

Repeatedly run a malloy notebook on a postgres database.  The notebook may need to have SQL errors in order to reproduce.  I haven't been able to pin point any specific conditions that could be triggering this behavior.

### OS:

Mac OS

### Malloy Client:

VS Code Notebook

### Malloy Client Version:

Latest VS Code  extension

### Database Connection:

Postgres

**Comment by whscullin** [comment]
I might need a little more detail here, I can't seem to reproduce this locally. If I bang on "Run" or "Run All" I get a number of connections to show up in netstat, but they're all in `TIME_WAIT` and drain off as expected after 30 seconds or so:
```
tcp4       0      0  127.0.0.1.5432         *.*                    LISTEN
tcp6       0      0  ::1.5432               *.*                    LISTEN
tcp6       0      0  ::1.61370              ::1.5432               TIME_WAIT
tcp6       0      0  ::1.61374              ::1.5432               TIME_WAIT
tcp6       0      0  ::1.61378              ::1.5432               TIME_WAIT
tcp6       0      0  ::1.61386              ::1.5432               TIME_WAIT
tcp6       0      0  ::1.61402              ::1.5432               TIME_WAIT
tcp6       0      0  ::1.61404              ::1.5432               TIME_WAIT
tcp6       0      0  ::1.61406              ::1.5432               TIME_WAIT
tcp6       0      0  ::1.61408              ::1.5432               TIME_WAIT
tcp6       0      0  ::1.61410              ::1.5432               TIME_WAIT
tcp6       0      0  ::1.61412              ::1.5432               TIME_WAIT
tcp6       0      0  ::1.61414              ::1.5432               TIME_WAIT
tcp6       0      0  ::1.61418              ::1.5432               TIME_WAIT
tcp6       0      0  ::1.61421              ::1.5432               TIME_WAIT
```
then
```
tcp4       0      0  127.0.0.1.5432         *.*                    LISTEN
tcp6       0      0  ::1.5432               *.*                    LISTEN
```
FWIW we're not using the pooled Postgres connection in the extension for some reason, it's probably worth it to do that anyway.

**Comment by kylenesbit** [comment]
I switched to the pre-release VS Code extension and haven't seen the error since.  I tried to reproduce by generating similar errors that I encountered when I was first setup on my Malloy notebook on notebook, but couldn't reproduce it.  I will close this out and will reopen it I encounter it again and have a better reproducer.  

Thank you for looking into it!
