### ISSUE TITLE
VS Code Malloy Runtime does not recognize new columns added during a session

### ISSUE THREAD

**Issue by kylenesbit** [malloydata/malloy#1440]
### What happens?

When I am working in Malloy VS Code, I do some analysis and realize I need to add a column to the underlying table.  

When I add the column, Malloy does not detect the new column and throws an error when I reference the column.

I have tried to refresh the Malloy schema using the circle arrow icon, but it doesn't seem to do anything.  I have to restart VS Code for the schema change to take effect.

### To Reproduce

Add a new column to a postgres table in the middle of a Malloy analysis.  Reference the new column in the analysis.  Try to refresh the schema.

### OS:

Mac OS

### Malloy Client:

Local VS Code

### Malloy Client Version:

Latest VS Code Extension

### Database Connection:

Postgres

**Comment by mtoy-googly-moogly** [comment]
Not sure of this is an extension or core issue. @whscullin  ?

**Comment by whscullin** [comment]
Yes. Fixed by and https://github.com/malloydata/malloy/pull/1441 and https://github.com/malloydata/malloy-vscode-extension/pull/298
