### ISSUE TITLE
Adding `# percent` to an aggregate makes the compiler think it is a dimension

### ISSUE THREAD

**Issue by kylenesbit** [malloydata/malloy#1454]
### What happens?

Here is the Malloy code
```
source: results is postgres.sql("SELECT * FROM retriever_eval_results") extend {
    measure:
        question_count is count()
        questions_with_all_tables is sum(pick 1 when jsonb_array_length!number(missing_tables) = 0 else 0)
        percent_questions_with_all_tables is questions_with_all_tables / question_count
}

source: configs is postgres.sql("SELECT * FROM retriever_eval_configs") extend {
    join_many: results on results.run_id = run_id
}

run: configs -> {
    group_by: run_id
    aggregate:
        results.question_count
        # percent
        results.percent_questions_with_all_tables
}
```
Here is the generated SQL:
```
WITH __stage0 AS (
  SELECT 
     configs."run_id" as "run_id",
     COUNT( 1) as "question_count",
     ((COALESCE(SUM(CASE WHEN (jsonb_array_length(results_0."missing_tables"))=0 THEN 1 ELSE 0 END),0))*1.0/(COUNT( 1))) as "percent_questions_with_all_tables"
  FROM (SELECT * FROM retriever_eval_configs) as configs
  LEFT JOIN (SELECT * FROM retriever_eval_results) AS results_0
    ON results_0."run_id"=configs."run_id"
  GROUP BY 1,3
  ORDER BY 2 desc NULLS LAST
)
SELECT row_to_json(finalStage) as row FROM __stage0 AS finalStage

Here is the error generated by Postgres
```
"aggregate functions are not allowed in GROUP BY"

It's unclear to me why Malloy is attempting to group on the measure percent_questions_with_all_tables.  It's possible I am doing something wrong.  If I am, it would be nice for Malloy to generate an error with details about what I am doing wrong rather than generating invalid SQL and the database returning an error.

### To Reproduce

See code above.

### OS:

Mac OS

### Malloy Client:

Local VS Code

### Malloy Client Version:

Latest pre-release VS Code extention

### Database Connection:

Postgres

**Comment by lloydtabb** [comment]
we'd need to see the schemas for each of these tables...  Can you post?

**Comment by kylenesbit** [comment]
Yes -- here's the relevant postion of the two table schema

        CREATE TABLE retriever_eval_results (
            missing_tables jsonb,
            run_id uuid REFERENCES retriever_eval_configs(run_id)
        );

        CREATE TABLE retriever_eval_configs (
            run_id uuid PRIMARY KEY,
            run_label text,
            run_timestamp timestamp,
            run_config jsonb
        );

Please let me know if you need anything else or help debugging.

**Comment by lloydtabb** [comment]
This is really strange.  Kyle and I rewrote as a join__one (starting from results) and everything worked fine.  Something is weird here...

**Comment by lloydtabb** [comment]
This is working for me.  @christopherswenson do you have any theories why this might fail?

```
source: a is postgres.sql("""
    SELECT * FROM 
  malloytest.airports
""") extend {
  measure: 
    c is count()
    s is sum(pick 1 when elevation > 500 else 0)
    d is s/c
}

source: b is postgres.sql("""
    SELECT * FROM 
  malloytest.airports
""") extend {
  join_many: a on state=a.state
}

run: b -> {
  group_by: state
  aggregate: a.c, a.d
}
```

**Comment by lloydtabb** [comment]
Kyle, can you swap out the tables for some arbitrary table?

**Comment by kylenesbit** [comment]
Sure thing!   I whittled it down to this reproducer.  However, if I remove the # percent tag, it passes!   Happy debugging. ;)

----------------------------------

CREATE TABLE table1 (id uuid);
CREATE TABLE table2 (id uuid);

----------------------------------

source: table1 is postgres.sql("SELECT * FROM table1") extend {
    measure:
        dummy_measure is sum(0) / count()
}

source: table2 is postgres.sql("SELECT * FROM table2") extend {
    primary_key: id
    join_many: table1 on table1.id = id
}

run: table2 -> {
    group_by: id
    aggregate:
        # percent
        table1.dummy_measure
}

**Comment by lloydtabb** [comment]
This isn't related to Postgres.  DuckDB has the same problem.

```
source: a is duckdb.table('../data/airports.parquet') extend {
  measure: 
    c is count()
    s is sum(pick 1 when abs!number(elevation) > 500 else 0)
    d is s/c
}

source: b is duckdb.table('../data/airports.parquet') extend {
  join_many: a on state=a.state
}

run: b -> {
  group_by: state
  aggregate: 
  a.c
  # percent
  a.d
}
```

**Comment by mtoy-googly-moogly** [comment]
As a workaround, if you NAME the `pct_question is results.percent_questions_with_all_tables` in the original or `ad is a.d` in the example, the query will work, I think.

Working on a fix.

**Comment by mtoy-googly-moogly** [comment]
ok, yes, when you annotate a reference, it creates a field to hold the annotation, and it doesn't correctly copy the field attributes to the new field
