### ISSUE TITLE
View limits don't override connection limits

### ISSUE THREAD

**Issue by skokenes** [malloydata/malloy#1486]
### What happens?

When running a view with an explicit limit set, the limit will be overridden by the default limit set for the database connection. I am not sure whether this is WAD or a bug.

### To Reproduce

Run in nodejs:
```javascript
const {DuckDBConnection} = require('@malloydata/db-duckdb');
const {SingleConnectionRuntime} = require('@malloydata/malloy');
const connection = new DuckDBConnection('duckdb');
const runtime = new SingleConnectionRuntime(connection);
const model = runtime.loadModel(`
source: x is duckdb.sql('SELECT * FROM range(0, 100, 1)')
`);
const runner = model.loadQuery(`run: x -> {
  select: *
  limit: 100
 }`);
runner.run().then(result => {
  console.log(result.totalRows); // prints 10 instead of 100
});
```

### OS:

OSX

### Malloy Client:

node

### Malloy Client Version:

dev

### Database Connection:

DuckDB

**Comment by mtoy-googly-moogly** [comment]
So ... in vs code ...

![image](https://github.com/malloydata/malloy/assets/66150587/e0ecb70f-39b5-40c4-91d8-9ae3d51ccdf9)

Curious what the query.getSQ

**Comment by whscullin** [comment]
The gotcha here is that the limit that's been enforced in the code snippet is a hard coded default in the connection that it's not clear that you need to override. Even in the places where we override it, like VS Code, it's still a small value (50). The SQL will be correct, but we'll still only return 50 row by default.

**Comment by mtoy-googly-moogly** [comment]
the sql though is always running with 100 rows, the limit is in how many rows of results we fetch, not in the SQL that we write.

**Comment by mtoy-googly-moogly** [comment]
Yes, the "view limit" is 100, that is what the SQL generates and what the server has ready to send.

For reasons, the api layer often fetches less than the full result. In this case, for reasons, it is only fetching 10.
