### ISSUE TITLE
Support something similar to PARTITION BY in SQL window functions

### ISSUE THREAD

**Issue by carlineng** [malloydata/malloy#1560]
Right now, analytic functions do not have the ability to contain `PARTITION BY` clauses to define the window on which they operate. Traditionally, we've recommended that people use nesting in place of `PARTITION BY` clauses, but this can result in some very awkward-looking Malloy queries. Take the following example:

I have a table that contains sales data over several years:
![image](https://github.com/malloydata/malloy/assets/79773/caa8dc37-d73e-4a3e-97bd-d81a9e83826a)

I want to calculate sales for each month, and compare to sales for that month in the prior year (i.e., a simple year-over-year analysis).

In SQL, I can write this like so:

```sql
select
  yr
  , mo
  , sum(rev) as this_year_rev
  , lag(sum(rev)) over (partition by mo order by yr) as last_year_rev
from 'output.parquet'
group by 1,2;
```

In Malloy, the same query must be written like so:
```
run: duckdb.table('output.parquet') -> {
  group_by: mo
  nest: n is {
    group_by: yr
    aggregate: this_year_rev is sum(rev)
    calculate: last_year_rev is lag(this_year_rev)
    order_by: yr asc
} -> {
  select: n.yr, mo, n.this_year_rev, n.last_year_rev
}
```

This is a really awkward query because it's forcing the user to think about nesting, but the desired output isn't a nested resultset. Instead, I'd like to be able to express something like the following (imagined syntax):

```
run: duckdb.table('output.parquet') -> {
  group_by: yr, mo
  aggregate: total_rev is sum(rev)
  calculate: l is lag(total_rev) { partition_by: mo, order_by: yr asc }
}
```

This fits my mental model of the query much better. The aggregate is happening at the year/month level, and the calculate is subsequently applied.

**Comment by lloydtabb** [comment]
I'm 100%, we should do this.  @christopherswenson @mtoy-googly-moogly
