### ISSUE TITLE
Aggregation on join_many returns wrong result

### ISSUE THREAD

**Issue by carlineng** [malloydata/malloy#1584]
### What happens?

I have a Source, `store` that does a `join_many` to `orders`. A store can have 0 or more orders. When I run a query on `store` that does a `count` on `orders`, I get a wrong result.

```
source: orders is duckdb.table('orders.parquet')

source: store is duckdb.table('stores.parquet') {
  join_many: orders on store_id = orders.store_id
}

run: store -> {
  aggregate: order_count is orders.count()
} -> {
  select: *
  where: order_count = 1
}
```

The query above will return rows for stores that do not appear in the `orders` table, and the `order_count` value for these stores will be 1. This is incorrect, the `order_count` value for these stores should be 0.

### To Reproduce

Run the query in this repo: https://github.com/wwasilak/Contoso_1M/blob/0d51a255eab8d5113b573e8e20fc5899bb6c5e8f/ContosoModel.malloy#L80-L92

### OS:

web

### Malloy Client:

web-based VSCode

### Malloy Client Version:

v0.2.1701793311

### Database Connection:

DuckDB

**Comment by lloydtabb** [comment]
fixed.

**Comment by lloydtabb** [comment]
fixed https://github.com/malloydata/malloy/pull/1585
