### ISSUE TITLE
Document `select *` in `SQL to Malloy`

### ISSUE THREAD

**Issue by abhillman** [malloydata/malloy#1730]
### What happens?

```
run: duckdb.table('output.parquet') -> {
  select: *
}
```

is not highlighted as incorrect by the IDE.

Bigger opportunity imo: https://docs.malloydata.dev/documentation/language/sql_to_malloy does not explain what the equivalent of `select *` is in malloy or (if it is not supported) whether there is some help in terms of automatically creating a field list for me. After all, malloy has access to my database, and it would make sense for there to be a code action to fill in a field list.

### To Reproduce

```
run: duckdb.table(<whatever>) -> {
  select: *
}
```

### OS:

does not matter

### Malloy Client:

does not matter

### Malloy Client Version:

v0.2.1712075074

### Database Connection:

duckdb

**Comment by mtoy-googly-moogly** [comment]
This works ...

![image](https://github.com/malloydata/malloy/assets/66150587/69c2da90-b45b-4de6-b7af-f47886de4137)

there is confusion on your or my part about that claim that `select: *` doesn't work.

**Comment by mtoy-googly-moogly** [comment]
Closing, feel free to re-open if you need to.
