### ISSUE TITLE
wrong sorting when nesting views

### ISSUE THREAD

**Issue by wwasilak** [malloydata/malloy#1927]
### What happens?

I am nesting two views in query. Each of those views is sorted by date field and when run separately the sorting works fine. The problem is, when nested in a query the sorting is broken (it also happens when only 1 view is nested):

![image](https://github.com/user-attachments/assets/b9af39b3-fc36-4064-8ee0-5e78a709502b)

### To Reproduce

view: base is {
    where: order_date >= @2024-07-31
        and (product_id = 441 | 493)
    group_by: 
            order_date
            flag is 1
    aggregate: 
            metric is total_quantity
    }
    
view: from_base1 is base ->
{
    group_by: order_date
    aggregate: total is  metric.sum()
    order_by: order_date asc
}

view: from_base2 is base ->
{
    group_by: order_date
    aggregate: flag.sum()
    order_by: order_date asc
}

view: nested is {
    where: order_date >= @2024-07-31
        and (product_id = 441 | 493)
    group_by: product_id
    aggregate: total_quantity
    nest: from_base1, from_base2
}

### OS:

Windows 10

### Malloy Client:

VSCode

### Malloy Client Version:

v0.3.1727197487 (pre-release)

### Database Connection:

DuckDB

**Comment by carlineng** [comment]
@wwasilak I'm having trouble reproducing this with our sample data. Are you willing to share the compiled SQL from when you run the `nested` view in the model above?

**Comment by carlineng** [comment]
@wwasilak thanks for the additional info. I was able repro in this query:

https://github.com/malloydata/malloy-samples/blob/7b1bfd6d50b3a4c11617e3f0ab9e998dc1936513/ecommerce/ecommerce.malloy#L237

**Comment by carlineng** [comment]
To add some color on what's happening -- it appears the ORDER BY clause in the nested view is not producing correct results, specifically when the nested view is a pipelined view, based off another view. In this example, `base` is a view, and `total_orders_v` is a view that starts with `base` and adds a pipeline segment.

**Comment by carlineng** [comment]
Super strange -- I can reproduce this behavior locally on the VS Code extension pre-release v0.3.1727197487; however, when I try to run it in the DuckDB-WASM version (also on pre-release v0.3.1727197487), I cannot reproduce.

**Comment by carlineng** [comment]
The query produces SQL that looks like the following:

```sql
WITH __stage0 AS (
  SELECT
    group_set,
    inventory_items_0."product_category" as "product_category__0",
    CASE WHEN group_set=0 THEN
      count(distinct order_items."order_id")
      END as "order_count__0",
    CASE WHEN group_set=1 THEN
      DATE_TRUNC('day', order_items."created_at")
      END as "order_date__1",
    CASE WHEN group_set=1 THEN
      count(distinct order_items."order_id")
      END as "order_count__1",
    CASE WHEN group_set=1 THEN
      COALESCE(SUM(order_items."sale_price"),0)
      END as "total_sales__1",
    CASE WHEN group_set=2 THEN
      DATE_TRUNC('day', order_items."created_at")
      END as "order_date__2",
    CASE WHEN group_set=2 THEN
      count(distinct order_items."order_id")
      END as "order_count__2",
    CASE WHEN group_set=2 THEN
      COALESCE(SUM(order_items."sale_price"),0)
      END as "total_sales__2"
  FROM '../data/order_items.parquet' as order_items
  LEFT JOIN '../data/inventory_items.parquet' AS inventory_items_0
    ON inventory_items_0."id"=order_items."inventory_item_id"
  CROSS JOIN (SELECT UNNEST(GENERATE_SERIES(0,2,1)) as group_set  ) as group_set
  WHERE ((group_set NOT IN (1) OR (group_set IN (1) AND (order_items."status"='Complete')and((DATE_TRUNC('day', order_items."created_at"))>=TIMESTAMP '2022-11-02 00:00:00'))))
  AND ((group_set NOT IN (2) OR (group_set IN (2) AND (order_items."status"='Complete')and((DATE_TRUNC('day', order_items."created_at"))>=TIMESTAMP '2022-11-02 00:00:00'))))
  GROUP BY 1,2,4,7
)

SELECT
  "product_category__0" as "product_category",
  (
    WITH __stage0 AS (
    SELECT 
       base."order_date" as "order_date",
       COALESCE(SUM(base."order_count"),0) as "order_count"
    FROM (SELECT UNNEST(COALESCE(LIST({
      "order_date": "order_date__2", 
      "order_count": "order_count__2", 
      "total_sales": "total_sales__2"}  ORDER BY  "order_date__2" desc NULLS LAST) FILTER (WHERE group_set=2),[])) as base) as base
    GROUP BY 1
    ORDER BY 1 asc NULLS LAST
  )
  SELECT LIST(ROW("order_date","order_count")) FROM __stage0
  ) as "total_orders_v"
FROM __stage0
GROUP BY 1
ORDER BY 2 desc NULLS LAST
```

I think the ordering from the inner list construction statement is not being preserved, and we need to add an additional ORDER BY in the outer one?

so instead of:
```sql
SELECT LIST(ROW("order_date","order_count")) FROM __stage0
```

we should write

```sql
SELECT LIST(ROW("order_date","order_count") ORDER BY "order_date") FROM __stage0
```
