### ISSUE TITLE
location connection parameter not being respected

### ISSUE THREAD

**Issue by anikaks** [malloydata/malloy#339]
The test connection is established correctly and the test query appears to run in the proper location. The queries generated run against BQ and in the project terminal, but lead to "dataset not found in location US" error in VSCode.

@christopherswenson has done some preliminary looking at this; assigning to you for now.

**Comment by jsbachsonata** [comment]
Hi I am experiencing the same issue! This makes the vscode plugin unusable for me unfortunately since all our data are not stored in US. I've tried setting a default compute region for my project too and that still doesn't work. It always tries to run queries in US.

**Comment by christopherswenson** [comment]
After you've changed the location configuration in connection configuration UI, can you reload VSCode (the "reload window" command after doing Command+Shift+P, or just restart the application) and see if it works then? I think what's happening is that the BigQuery connection is being created with the default (US) location, and then when you set it to something else, it doesn't actually update.
