### ISSUE TITLE
Feature request ; Level of Details Calculation. 

### ISSUE THREAD

**Issue by djouallah** [malloydata/malloy#404]
add level of details calculation in Malloy, a typical use case, is sum all, which basically return the total sum regardless of the grouping, is this something already supported, otherwise what's the plan if not

**Comment by anikaks** [comment]
Hey @djouallah,  If I'm understanding what you're asking for, I believe something like this should get you the calculation you want:
```
query: table('malloy-data.faa.airports') -> {
  nest: airports_by_state is {
    group_by: state
    aggregate: airport_count is count()
  }
  aggregate: total_airport_count is count()
}
```

Or was there something different you had in mind?

**Comment by anikaks** [comment]
Also worth checking out [Aggregate Locality](https://looker-open-source.github.io/malloy/documentation/language/aggregates.html#aggregate-locality)  - I believe this may be along the lines of what you're looking for and should give you a lot of flexibility about how/where to aggregate.

**Comment by djouallah** [comment]
@anikaks   thanks, but maybe, it will be nice if it is defined at the measure level not in the Query

maybe something like total_airport_count is count(), all(), so it does ignore aggregation regardless of the Query used ?

**Comment by anikaks** [comment]
@lloydtabb and I were talking about this today; there's definitely something there in navigating the aggregate locality / aggregating without grouping. Thanks for the feature request!
