### ISSUE TITLE
Feature request: enable duckdb httpfs extension

### ISSUE THREAD

**Issue by kj-9** [malloydata/malloy#633]
I'd like to run a duckdb query against http hosted csv files.
This is one of my favorite features of duckdb. (and hopefully for others too)

For example:
```
sql: covid_jp_daily is ||
  select *
  from 'https://raw.githubusercontent.com/kj-9/covid19jp/master/data-raw/dist/jp_daily.csv'
  limit 10
;;
```
Running this on malloy extention throws the error:
> lookup.message.includes is not a function

Seems like to do this, we need to enable httpfs extension by [INSTALL and LOAD statement](https://duckdb.org/docs/extensions/overview) .

P.S.
I enjoy using Malloy and exploring repo. Thank you for developing and open-sourcing this repo!

**Comment by lloydtabb** [comment]
I looked at this before, but found the fetching unreliable (which caused problems).  We can take a look at this again...

**Comment by whscullin** [comment]
One of the main challenges for us using extensions is that we are currently using development versions of duckdb to have the latest features and bug fixes, but extensions often don't seem to be available for these releases (the extensions are tied to a specific git commit hash, not just a major/minor version). If we are able to land on a release version of duckdb we can consider what extensions we want to support.
