### ISSUE TITLE
Documentation : Show example of cumulative sum 

### ISSUE THREAD

**Issue by djouallah** [malloydata/malloy#676]
there is a joke that 90 % of analytical uses cases can be solved by All and cumulative sum, All is well understood and documented, not sure how Malloy Support cumulative sum, an example in the documentation will be great

**Comment by lloydtabb** [comment]
Currently we are missing a bunch of window functions, including cumulative sum.  We're not quite sure how we want to represent this in the language so we haven't done it yet.  Sorry.
