### ISSUE TITLE
DuckDB does not work with local path if it contain * 

### ISSUE THREAD

**Issue by djouallah** [malloydata/malloy#722]
for example 

this path give errors : source:lineitem is table('duckdb:Parquet/lineitem/*.parquet')

although this one works fine :  source:lineitem is table('duckdb:Parquet/lineitem/lineitem.parquet')

**Comment by whscullin** [comment]
Right now in order for file globing to work you need to use absolute paths. Behind the scenes with DuckDB we use `file_search_path` for relative paths, and that wasn't incorporated into into the globing logic. I've opened a PR against DuckDB to do that, so if that is accepted we will pick that up in the not too distant future.

**Comment by whscullin** [comment]
The fix has been merged into duckdb and will be available once the the next release is integrated into Malloy.

**Comment by whscullin** [comment]
With https://github.com/malloydata/malloy/pull/958 Malloy has been updated with the latest duckdb that includes these changes, and updated to better support table names with wildcards. These changes have been merged into the VSCode extension (https://github.com/malloydata/malloy-vscode-extension/pull/25) and and Composer (https://github.com/malloydata/malloy-composer/pull/92)
