### ISSUE TITLE
Schema error: unknown postgres type USER-DEFINED

### ISSUE THREAD

**Issue by jschaf** [malloydata/malloy#918]
I have a schema that uses tstzrange, an enum, and a domain type. One of them causes the VSCode extension to error with:

```
Schema error: unknown postgres type USER-DEFINED
```

I'm happy to send a PR to modify postgres_connection.ts to support those types if you're interested. I'm familiar with Postgres types by virtue of maintaining [pggen](https://github.com/jschaf/pggen).

If that sounds good, my high-level plan for a PR is:

1. Use the postgres catalog tables directly instead of information schemas. Has a minor benefit of being faster and supporting postgres specific features.
2. Remove the temp table. I might have missed something but it appears that postgres_connection creates a new random temp table every time it's invoked that's never used again.
3. Make sure enums translate into a text type.

### Questions

- What should `tstzrange` translate to? 
- Is it reasonable to drop unknown columns rather than error out? I'm not sure how that would interact with projecting `*`.
- Is there a way to test Postgres integration?

**Comment by lloydtabb** [comment]
@mtoy-googly-moogly @christopherswenson and I have been talking about this.  We're going to add an 'unknown' type in Malloy that should allow access to these fields.  We can then skip them in `project: *` and the like.

> What should tstzrange translate to?
Wow, interesting.  @mtoy-googly-moogly is this a partial?

> Is it reasonable to drop unknown columns rather than error out? I'm not sure how that would interact with projecting *.
Yes, once we have an 'unknown' type we should drop in project

> Is there a way to test Postgres integration?
Yes.  The test data we use for postgres is here: 

  https://github.com/looker-open-source/malloy/tree/main/test/data/postgres

Unfortunately we don't have a public postgres server...  It isn't something Google would be happy about.

**Comment by lloydtabb** [comment]
A ppgen looks really cool..   Someday we'd love to have something like it for Malloy.  

 I'd love to chat with you if you are willing.  Our current Postgres implementation Postgres's user types isn't all that great.   Perhaps join our slack comminity and we can chat or setup a time to talk?  

  https://join.slack.com/t/malloy-community/shared_invite/zt-upi18gic-W2saeFu~VfaVM1~HIerJ7w

**Comment by mtoy-googly-moogly** [comment]
@jschaf would love to help you on getting to a PR that works for you. Feel free to grab me on the slack, even for stupid little questions. I'm `@Michael Toy` on slack.

**Comment by mtoy-googly-moogly** [comment]
As for your plan.

1) Absolutely great idea to drop information schema. No reason for us to prefer INFORMATION_SCHEMA that I am aware of.
2) That's a @lloydtabb thing that I can't say anything wise about.
3) We do have a range type internally in the compiler, I expect if we just made the schema reader return a range type it would NOT work smoothly, but it feels like the right thing is then to make that work.

**Comment by mtoy-googly-moogly** [comment]
@jschaf I've got #920 up to stop throwing an error on unknown types in the schema, should get merged today.

**Comment by mtoy-googly-moogly** [comment]
@jschaf that's merged now ... for sure in pre-release vs-code and i think it might even be in release at this point.

**Comment by bporterfield** [comment]
looks like this is handled, closing, but feel free to-reopen if there are outstanding issues
