### ISSUE TITLE
Allow more characters in quoted field names.

### ISSUE THREAD

**Issue by lloydtabb** [malloydata/malloy#944]
Here is an example of a dataset I'm trying to query....

![image](https://user-images.githubusercontent.com/1093458/204612257-d5b40462-991e-493d-8f75-d98ec800b558.png)

**Comment by mtoy-googly-moogly** [comment]
This is fixed in the language in #945. It may need help in the various editors.

**Comment by mtoy-googly-moogly** [comment]
Actually this is fixed in malloy-the-language. I'll file a bug against the IDE.
