### ISSUE TITLE
Error resolving relative .malloy file import in VSCode extension on windows

### ISSUE THREAD

**Issue by RandomFractals** [malloydata/malloy#963]
I ran into this issue recently after VSCode IDE and Malloy extension update. This functionality used to work in Malloy extension with `./` and without `./` relative path reference just a week ago prior to those updates.

In my Chicago crimes data repo, I am importing base model for that data to create charts in another malloy config file.

That import now shows an error resolving relative file path for Malloy file imports. This might be Windows specific. As you can see in the screenshot below it doesn't generate correct absolute file path for the `E:/` drive where I have my projects stored.

You can try it by cloning my repo, and opening this `.malloy` file in VSCode IDE:

https://github.com/RandomFractals/chicago-crimes/blob/main/scripts/chicago-crime-charts-2022.malloy

![malloy-import-error](https://user-images.githubusercontent.com/656833/206868893-72a698b2-c7ea-4499-8038-65e45376a3db.png)

Malloy ext. version: v0.2.1670328727

VSCode version info:

Version: 1.74.0 (user setup)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:38:16.075Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

**Comment by whscullin** [comment]
I was able to reproduce the first issue fairly easily, it seems like the breakage was fairly old, possibly having different files open in VSCode made it come and go. I think I should have a fix shortly with https://github.com/malloydata/malloy-vscode-extension/pull/31

**Comment by whscullin** [comment]
Closed by https://github.com/malloydata/malloy-vscode-extension/pull/31
